### ISSUE TITLE
Example code is not working

### ISSUE THREAD

**Issue by ebonynon** [keroxp/servest#115]
When I run an example code  ,

```typescript
// @deno-types="https://servestjs.org/@/types/react/index.d.ts"
import React from "https://dev.jspm.io/react/index.js";
// @deno-types="https://servestjs.org/@/types/react-dom/server/index.d.ts"
import ReactDOMServer from "https://dev.jspm.io/react-dom/server.js";
import { createApp } from "https://servestjs.org/@/mod.ts";

const app = createApp();
app.handle("/", async req => {
  await req.respond({
    status: 200,
    headers: new Headers({
      "content-type": "text/html; charset=UTF-8"
    }),
    body: ReactDOMServer.renderToString(
      <html>
        <head>
          <meta charSet="utf-8" />
          <title>servest</title>
        </head>
        <body>Hello Servest!</body>
      </html>
    )
  });
});


app.listen({port: 8888});
```

It gives this error

```
 /tmp  deno run example.ts                               Sat 16 May 2020 04:06:10 PM +0530
Compile file:///tmp/example.ts
error: TS2304 [ERROR]: Cannot find name 'html'.
      <html>
       ~~~~
    at file:///tmp/example.ts:15:8

TS2304 [ERROR]: Cannot find name 'head'.
        <head>
         ~~~~
    at file:///tmp/example.ts:16:10

TS2304 [ERROR]: Cannot find name 'meta'.
          <meta charSet="utf-8" />
           ~~~~
    at file:///tmp/example.ts:17:12

TS1005 [ERROR]: '>' expected.
          <meta charSet="utf-8" />
                ~~~~~~~
    at file:///tmp/example.ts:17:17

TS2304 [ERROR]: Cannot find name 'charSet'.
          <meta charSet="utf-8" />
                ~~~~~~~
    at file:///tmp/example.ts:17:17

TS1005 [ERROR]: ',' expected.
          <meta charSet="utf-8" />
                       ^
    at file:///tmp/example.ts:17:24

TS2362 [ERROR]: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
          <meta charSet="utf-8" />
                        ~~~~~~~
    at file:///tmp/example.ts:17:25

TS2365 [ERROR]: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.
          <meta charSet="utf-8" />
                        
    at file:///tmp/example.ts:17:25

TS2365 [ERROR]: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.
          <meta charSet="utf-8" />
                        
    at file:///tmp/example.ts:17:25

TS2554 [ERROR]: Expected 1 arguments, but got 3.
          <meta charSet="utf-8" />
                        
    at file:///tmp/example.ts:17:25

TS1109 [ERROR]: Expression expected.
          <meta charSet="utf-8" />
                                 ^
    at file:///tmp/example.ts:17:34

TS2304 [ERROR]: Cannot find name 'title'.
          <title>servest</title>
           ~~~~~
    at file:///tmp/example.ts:18:12

TS2304 [ERROR]: Cannot find name 'servest'.
          <title>servest</title>
                 ~~~~~~~
    at file:///tmp/example.ts:18:18

TS1161 [ERROR]: Unterminated regular expression literal.
    at 

TS1161 [ERROR]: Unterminated regular expression literal.
    at 

TS2304 [ERROR]: Cannot find name 'body'.
        <body>Hello Servest!</body>
         ~~~~
    at file:///tmp/example.ts:20:10

TS2304 [ERROR]: Cannot find name 'Hello'.
        <body>Hello Servest!</body>
              ~~~~~
    at file:///tmp/example.ts:20:15

TS1005 [ERROR]: ',' expected.
        <body>Hello Servest!</body>
                    ~~~~~~~
    at file:///tmp/example.ts:20:21

TS2304 [ERROR]: Cannot find name 'Servest'.
        <body>Hello Servest!</body>
                    ~~~~~~~
    at file:///tmp/example.ts:20:21

TS2365 [ERROR]: Operator '<' cannot be applied to types 'boolean' and 'RegExp'.
        <body>Hello Servest!</body>
                    
    at file:///tmp/example.ts:20:21

TS1161 [ERROR]: Unterminated regular expression literal.
    at 

TS1161 [ERROR]: Unterminated regular expression literal.
    at 

Found 22 errors.
 ```

I think there is a problem with ReactDOMServer

**Comment by keroxp** [comment]
@ebonynon Did you save code as `.tsx` file?  `.ts` file can't have jsx syntax in Deno.

**Comment by ebonynon** [comment]
Oh my bad
