### ISSUE TITLE
Some issues with unstable 1.4 runtime 

### ISSUE THREAD

**Issue by cz35iek** [keroxp/servest#141]
After running unstable 1.4.2 deno runtime I'm getting following errors ->
deno run --unstable server.ts -A

Check file:///C:/repo/legal-paper/server.ts
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { BodyReader } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/_readers.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import {
^
    at https://servestjs.org/@v1.1.5/serveio.ts:19:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ServerResponse, HttpBody } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/responder.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { BodyParser } from "./body_parser.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/server.ts:11:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ClientResponse, HttpBody } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/agent.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ServerRequest, ServeHandler } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/router.ts:5:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { FC } from "./types/react/index.d.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/jsx.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ServeHandler } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/middleware.ts:5:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ServeHandler } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/serve_jsx.ts:4:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { DFC } from "./jsx.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/serve_jsx.ts:6:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { ServeHandler } from "./server.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://servestjs.org/@v1.1.5/serve_static.ts:4:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import {
^
    at https://servestjs.org/@v1.1.5/testing.ts:6:1

Found 12 errors.

**Comment by cz35iek** [comment]
I can help fixing this

**Comment by keroxp** [comment]
@cz35iek I couldn't reproduce those errors by adding `--unstabe` flag. Could you check the latest deno release? (1.4.5)
